05/03

diff --git a/dot_config/lf/executable_scope b/dot_config/lf/executable_scope
--- a/dot_config/lf/executable_scope
+++ b/dot_config/lf/executable_scope
@@ -8,9 +8,10 @@ IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"
 image() {
 	if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
 		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
-	else
+  elif [ -n "$WAYLAND_DISPLAY" ]; then
      chafa "$1" -f sixel -s "$(($2-2))x$(($3-2))" | sed 's/#/\n#/g'
-		# mediainfo "$6"
+  else
+		mediainfo "$6"
 	fi
 }
 
@@ -21,7 +22,6 @@ ifub() {
 # Note that the cache file name is a function of file information, meaning if
 # an image appears in multiple places across the machine, it will not have to
 # be regenerated once seen.
-
 case "$(file --dereference --brief --mime-type -- "$1")" in
 	image/avif) CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
 		[ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
@@ -51,4 +51,5 @@ case "$(file --dereference --brief --mime-type -- "$1")" in
 	application/pgp-encrypted) gpg -d -- "$1" ;;
   application/vnd.sqlite3) echo .schema | sqlite3 -- "$1" | bat -l sql ;;
 esac
-exit 1
+# this tells lf to clean up on xorg
+#exit 1
